wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1660151689
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 19
      4: 3.8.12
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0003
